//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmemeTransactionService.UmemeBillingInterface {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://UmemeEPayment/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReceiptNumber {
            get {
                return this.ReceiptNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptNumberField, value) != true)) {
                    this.ReceiptNumberField = value;
                    this.RaisePropertyChanged("ReceiptNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://UmemeEPayment/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTypeField;
        
        private double BalanceField;
        
        private double CreditField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerRef {
            get {
                return this.CustomerRefField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerRefField, value) != true)) {
                    this.CustomerRefField = value;
                    this.RaisePropertyChanged("CustomerRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://UmemeEPayment/")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DigitalSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranNarrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorTranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranIdToReverseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReversalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfflineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TranId {
            get {
                return this.TranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TranIdField, value) != true)) {
                    this.TranIdField = value;
                    this.RaisePropertyChanged("TranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DigitalSignature {
            get {
                return this.DigitalSignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.DigitalSignatureField, value) != true)) {
                    this.DigitalSignatureField = value;
                    this.RaisePropertyChanged("DigitalSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDateField, value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TranAmount {
            get {
                return this.TranAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TranAmountField, value) != true)) {
                    this.TranAmountField = value;
                    this.RaisePropertyChanged("TranAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Teller {
            get {
                return this.TellerField;
            }
            set {
                if ((object.ReferenceEquals(this.TellerField, value) != true)) {
                    this.TellerField = value;
                    this.RaisePropertyChanged("Teller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string VendorCode {
            get {
                return this.VendorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorCodeField, value) != true)) {
                    this.VendorCodeField = value;
                    this.RaisePropertyChanged("VendorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TranNarration {
            get {
                return this.TranNarrationField;
            }
            set {
                if ((object.ReferenceEquals(this.TranNarrationField, value) != true)) {
                    this.TranNarrationField = value;
                    this.RaisePropertyChanged("TranNarration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string VendorTranId {
            get {
                return this.VendorTranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorTranIdField, value) != true)) {
                    this.VendorTranIdField = value;
                    this.RaisePropertyChanged("VendorTranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TranIdToReverse {
            get {
                return this.TranIdToReverseField;
            }
            set {
                if ((object.ReferenceEquals(this.TranIdToReverseField, value) != true)) {
                    this.TranIdToReverseField = value;
                    this.RaisePropertyChanged("TranIdToReverse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TranType {
            get {
                return this.TranTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranTypeField, value) != true)) {
                    this.TranTypeField = value;
                    this.RaisePropertyChanged("TranType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CustomerRef {
            get {
                return this.CustomerRefField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerRefField, value) != true)) {
                    this.CustomerRefField = value;
                    this.RaisePropertyChanged("CustomerRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string CustomerTel {
            get {
                return this.CustomerTelField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTelField, value) != true)) {
                    this.CustomerTelField = value;
                    this.RaisePropertyChanged("CustomerTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Reversal {
            get {
                return this.ReversalField;
            }
            set {
                if ((object.ReferenceEquals(this.ReversalField, value) != true)) {
                    this.ReversalField = value;
                    this.RaisePropertyChanged("Reversal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Offline {
            get {
                return this.OfflineField;
            }
            set {
                if ((object.ReferenceEquals(this.OfflineField, value) != true)) {
                    this.OfflineField = value;
                    this.RaisePropertyChanged("Offline");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://UmemeEPayment/")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemainingCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LifeLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebtRecoveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InflationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrepaidTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RemainingCredit {
            get {
                return this.RemainingCreditField;
            }
            set {
                if ((object.ReferenceEquals(this.RemainingCreditField, value) != true)) {
                    this.RemainingCreditField = value;
                    this.RaisePropertyChanged("RemainingCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LifeLine {
            get {
                return this.LifeLineField;
            }
            set {
                if ((object.ReferenceEquals(this.LifeLineField, value) != true)) {
                    this.LifeLineField = value;
                    this.RaisePropertyChanged("LifeLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ServiceFee {
            get {
                return this.ServiceFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceFeeField, value) != true)) {
                    this.ServiceFeeField = value;
                    this.RaisePropertyChanged("ServiceFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PayAccount {
            get {
                return this.PayAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PayAccountField, value) != true)) {
                    this.PayAccountField = value;
                    this.RaisePropertyChanged("PayAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DebtRecovery {
            get {
                return this.DebtRecoveryField;
            }
            set {
                if ((object.ReferenceEquals(this.DebtRecoveryField, value) != true)) {
                    this.DebtRecoveryField = value;
                    this.RaisePropertyChanged("DebtRecovery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ReceiptNumber {
            get {
                return this.ReceiptNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptNumberField, value) != true)) {
                    this.ReceiptNumberField = value;
                    this.RaisePropertyChanged("ReceiptNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MeterNumber {
            get {
                return this.MeterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNumberField, value) != true)) {
                    this.MeterNumberField = value;
                    this.RaisePropertyChanged("MeterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitsField, value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TokenValue {
            get {
                return this.TokenValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenValueField, value) != true)) {
                    this.TokenValueField = value;
                    this.RaisePropertyChanged("TokenValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Inflation {
            get {
                return this.InflationField;
            }
            set {
                if ((object.ReferenceEquals(this.InflationField, value) != true)) {
                    this.InflationField = value;
                    this.RaisePropertyChanged("Inflation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxField, value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Fx {
            get {
                return this.FxField;
            }
            set {
                if ((object.ReferenceEquals(this.FxField, value) != true)) {
                    this.FxField = value;
                    this.RaisePropertyChanged("Fx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Fuel {
            get {
                return this.FuelField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelField, value) != true)) {
                    this.FuelField = value;
                    this.RaisePropertyChanged("Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalAmountField, value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string PrepaidToken {
            get {
                return this.PrepaidTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.PrepaidTokenField, value) != true)) {
                    this.PrepaidTokenField = value;
                    this.RaisePropertyChanged("PrepaidToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UmemeEPayment/", ConfigurationName="UmemeBillingInterface.EPaymentSoap")]
    public interface EPaymentSoap {
        
        // CODEGEN: Generating message contract since element name vendorTranID from namespace http://UmemeEPayment/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/GetTransactionDetails", ReplyAction="*")]
        UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponse GetTransactionDetails(UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/GetTransactionDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponse> GetTransactionDetailsAsync(UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetServerStatusResult from namespace http://UmemeEPayment/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/GetServerStatus", ReplyAction="*")]
        UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponse GetServerStatus(UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/GetServerStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponse> GetServerStatusAsync(UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest request);
        
        // CODEGEN: Generating message contract since element name customerRef from namespace http://UmemeEPayment/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/ValidateCustomer", ReplyAction="*")]
        UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponse ValidateCustomer(UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/ValidateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponse> ValidateCustomerAsync(UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name trans from namespace http://UmemeEPayment/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/PostUmemePayment", ReplyAction="*")]
        UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponse PostUmemePayment(UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/PostUmemePayment", ReplyAction="*")]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponse> PostUmemePaymentAsync(UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest request);
        
        // CODEGEN: Generating message contract since element name trans from namespace http://UmemeEPayment/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/PostYakaPayment", ReplyAction="*")]
        UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponse PostYakaPayment(UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/PostYakaPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponse> PostYakaPaymentAsync(UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name trans from namespace http://UmemeEPayment/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/PostBankUmemePayment", ReplyAction="*")]
        UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponse PostBankUmemePayment(UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UmemeEPayment/PostBankUmemePayment", ReplyAction="*")]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponse> PostBankUmemePaymentAsync(UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransactionDetails", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequestBody Body;
        
        public GetTransactionDetailsRequest() {
        }
        
        public GetTransactionDetailsRequest(UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class GetTransactionDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vendorTranID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vendorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetTransactionDetailsRequestBody() {
        }
        
        public GetTransactionDetailsRequestBody(string vendorTranID, string vendorCode, string password) {
            this.vendorTranID = vendorTranID;
            this.vendorCode = vendorCode;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransactionDetailsResponse", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponseBody Body;
        
        public GetTransactionDetailsResponse() {
        }
        
        public GetTransactionDetailsResponse(UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class GetTransactionDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Response GetTransactionDetailsResult;
        
        public GetTransactionDetailsResponseBody() {
        }
        
        public GetTransactionDetailsResponseBody(UmemeTransactionService.UmemeBillingInterface.Response GetTransactionDetailsResult) {
            this.GetTransactionDetailsResult = GetTransactionDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerStatus", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequestBody Body;
        
        public GetServerStatusRequest() {
        }
        
        public GetServerStatusRequest(UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetServerStatusRequestBody {
        
        public GetServerStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerStatusResponse", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponseBody Body;
        
        public GetServerStatusResponse() {
        }
        
        public GetServerStatusResponse(UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class GetServerStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServerStatusResult;
        
        public GetServerStatusResponseBody() {
        }
        
        public GetServerStatusResponseBody(string GetServerStatusResult) {
            this.GetServerStatusResult = GetServerStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCustomer", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequestBody Body;
        
        public ValidateCustomerRequest() {
        }
        
        public ValidateCustomerRequest(UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class ValidateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerRef;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vendorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public ValidateCustomerRequestBody() {
        }
        
        public ValidateCustomerRequestBody(string customerRef, string vendorCode, string password) {
            this.customerRef = customerRef;
            this.vendorCode = vendorCode;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCustomerResponse", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponseBody Body;
        
        public ValidateCustomerResponse() {
        }
        
        public ValidateCustomerResponse(UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class ValidateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Customer ValidateCustomerResult;
        
        public ValidateCustomerResponseBody() {
        }
        
        public ValidateCustomerResponseBody(UmemeTransactionService.UmemeBillingInterface.Customer ValidateCustomerResult) {
            this.ValidateCustomerResult = ValidateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostUmemePaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostUmemePayment", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequestBody Body;
        
        public PostUmemePaymentRequest() {
        }
        
        public PostUmemePaymentRequest(UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class PostUmemePaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Transaction trans;
        
        public PostUmemePaymentRequestBody() {
        }
        
        public PostUmemePaymentRequestBody(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            this.trans = trans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostUmemePaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostUmemePaymentResponse", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponseBody Body;
        
        public PostUmemePaymentResponse() {
        }
        
        public PostUmemePaymentResponse(UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class PostUmemePaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Response PostUmemePaymentResult;
        
        public PostUmemePaymentResponseBody() {
        }
        
        public PostUmemePaymentResponseBody(UmemeTransactionService.UmemeBillingInterface.Response PostUmemePaymentResult) {
            this.PostUmemePaymentResult = PostUmemePaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostYakaPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostYakaPayment", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequestBody Body;
        
        public PostYakaPaymentRequest() {
        }
        
        public PostYakaPaymentRequest(UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class PostYakaPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Transaction trans;
        
        public PostYakaPaymentRequestBody() {
        }
        
        public PostYakaPaymentRequestBody(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            this.trans = trans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostYakaPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostYakaPaymentResponse", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponseBody Body;
        
        public PostYakaPaymentResponse() {
        }
        
        public PostYakaPaymentResponse(UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class PostYakaPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Token PostYakaPaymentResult;
        
        public PostYakaPaymentResponseBody() {
        }
        
        public PostYakaPaymentResponseBody(UmemeTransactionService.UmemeBillingInterface.Token PostYakaPaymentResult) {
            this.PostYakaPaymentResult = PostYakaPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostBankUmemePaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostBankUmemePayment", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequestBody Body;
        
        public PostBankUmemePaymentRequest() {
        }
        
        public PostBankUmemePaymentRequest(UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class PostBankUmemePaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Transaction trans;
        
        public PostBankUmemePaymentRequestBody() {
        }
        
        public PostBankUmemePaymentRequestBody(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            this.trans = trans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostBankUmemePaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostBankUmemePaymentResponse", Namespace="http://UmemeEPayment/", Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponseBody Body;
        
        public PostBankUmemePaymentResponse() {
        }
        
        public PostBankUmemePaymentResponse(UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://UmemeEPayment/")]
    public partial class PostBankUmemePaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UmemeTransactionService.UmemeBillingInterface.Response PostBankUmemePaymentResult;
        
        public PostBankUmemePaymentResponseBody() {
        }
        
        public PostBankUmemePaymentResponseBody(UmemeTransactionService.UmemeBillingInterface.Response PostBankUmemePaymentResult) {
            this.PostBankUmemePaymentResult = PostBankUmemePaymentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EPaymentSoapChannel : UmemeTransactionService.UmemeBillingInterface.EPaymentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EPaymentSoapClient : System.ServiceModel.ClientBase<UmemeTransactionService.UmemeBillingInterface.EPaymentSoap>, UmemeTransactionService.UmemeBillingInterface.EPaymentSoap {
        
        public EPaymentSoapClient() {
        }
        
        public EPaymentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EPaymentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPaymentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPaymentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponse UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.GetTransactionDetails(UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest request) {
            return base.Channel.GetTransactionDetails(request);
        }
        
        public UmemeTransactionService.UmemeBillingInterface.Response GetTransactionDetails(string vendorTranID, string vendorCode, string password) {
            UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest inValue = new UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequestBody();
            inValue.Body.vendorTranID = vendorTranID;
            inValue.Body.vendorCode = vendorCode;
            inValue.Body.password = password;
            UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponse retVal = ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).GetTransactionDetails(inValue);
            return retVal.Body.GetTransactionDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponse> UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.GetTransactionDetailsAsync(UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest request) {
            return base.Channel.GetTransactionDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsResponse> GetTransactionDetailsAsync(string vendorTranID, string vendorCode, string password) {
            UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest inValue = new UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.GetTransactionDetailsRequestBody();
            inValue.Body.vendorTranID = vendorTranID;
            inValue.Body.vendorCode = vendorCode;
            inValue.Body.password = password;
            return ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).GetTransactionDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponse UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.GetServerStatus(UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest request) {
            return base.Channel.GetServerStatus(request);
        }
        
        public string GetServerStatus() {
            UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest inValue = new UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequestBody();
            UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponse retVal = ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).GetServerStatus(inValue);
            return retVal.Body.GetServerStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponse> UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.GetServerStatusAsync(UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest request) {
            return base.Channel.GetServerStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.GetServerStatusResponse> GetServerStatusAsync() {
            UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest inValue = new UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.GetServerStatusRequestBody();
            return ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).GetServerStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponse UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.ValidateCustomer(UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest request) {
            return base.Channel.ValidateCustomer(request);
        }
        
        public UmemeTransactionService.UmemeBillingInterface.Customer ValidateCustomer(string customerRef, string vendorCode, string password) {
            UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest inValue = new UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequestBody();
            inValue.Body.customerRef = customerRef;
            inValue.Body.vendorCode = vendorCode;
            inValue.Body.password = password;
            UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponse retVal = ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).ValidateCustomer(inValue);
            return retVal.Body.ValidateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponse> UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.ValidateCustomerAsync(UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest request) {
            return base.Channel.ValidateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.ValidateCustomerResponse> ValidateCustomerAsync(string customerRef, string vendorCode, string password) {
            UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest inValue = new UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.ValidateCustomerRequestBody();
            inValue.Body.customerRef = customerRef;
            inValue.Body.vendorCode = vendorCode;
            inValue.Body.password = password;
            return ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).ValidateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponse UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.PostUmemePayment(UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest request) {
            return base.Channel.PostUmemePayment(request);
        }
        
        public UmemeTransactionService.UmemeBillingInterface.Response PostUmemePayment(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest inValue = new UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequestBody();
            inValue.Body.trans = trans;
            UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponse retVal = ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).PostUmemePayment(inValue);
            return retVal.Body.PostUmemePaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponse> UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.PostUmemePaymentAsync(UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest request) {
            return base.Channel.PostUmemePaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentResponse> PostUmemePaymentAsync(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest inValue = new UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.PostUmemePaymentRequestBody();
            inValue.Body.trans = trans;
            return ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).PostUmemePaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponse UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.PostYakaPayment(UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest request) {
            return base.Channel.PostYakaPayment(request);
        }
        
        public UmemeTransactionService.UmemeBillingInterface.Token PostYakaPayment(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest inValue = new UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequestBody();
            inValue.Body.trans = trans;
            UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponse retVal = ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).PostYakaPayment(inValue);
            return retVal.Body.PostYakaPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponse> UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.PostYakaPaymentAsync(UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest request) {
            return base.Channel.PostYakaPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentResponse> PostYakaPaymentAsync(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest inValue = new UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.PostYakaPaymentRequestBody();
            inValue.Body.trans = trans;
            return ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).PostYakaPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponse UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.PostBankUmemePayment(UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest request) {
            System.Net.ServicePointManager.ServerCertificateValidationCallback += delegate { return true; };
            return base.Channel.PostBankUmemePayment(request);
        }
        
        public UmemeTransactionService.UmemeBillingInterface.Response PostBankUmemePayment(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest inValue = new UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequestBody();
            inValue.Body.trans = trans;
            UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponse retVal = ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).PostBankUmemePayment(inValue);
            return retVal.Body.PostBankUmemePaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponse> UmemeTransactionService.UmemeBillingInterface.EPaymentSoap.PostBankUmemePaymentAsync(UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest request) {
            return base.Channel.PostBankUmemePaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentResponse> PostBankUmemePaymentAsync(UmemeTransactionService.UmemeBillingInterface.Transaction trans) {
            UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest inValue = new UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequest();
            inValue.Body = new UmemeTransactionService.UmemeBillingInterface.PostBankUmemePaymentRequestBody();
            inValue.Body.trans = trans;
            return ((UmemeTransactionService.UmemeBillingInterface.EPaymentSoap)(this)).PostBankUmemePaymentAsync(inValue);
        }
    }
}
